### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by zwanzigg** [zwanzigg/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by dasha-korotkykh** [comment]
Хей, привіт! Якщо ти складаєш резюме про себе чи улюбленого персонажа/людину, тобі потрібно написати цей контент самостiйно, я буду рада його продивитися і порадити щось, якщо буде потрібно. Якщо ти складаєш сторінку на замовлення Рю або Дональда, тобі потрібно взяти інформацію з їхніх файлів відповідно, які вказані в описі завдання. Знаєш де лінки на ті файли, чи скинути тобі? :)
P.S. те саме стосується і інших issues

**Comment by zwanzigg** [comment]
О, я поняла, линки есть, спасибо за фидбек :)

**Comment by zwanzigg** [comment]
<div class="skills">
                        <h2>Additional information</h2>

                        <div class="skill_wrap">
                            <p class="animated rotateInDownLeft">LANGUAGES </p>
                            <span>
							ðŸ‡ºðŸ‡¸ ENGLISH ðŸ‡·ðŸ‡º RUSSIAN
						</span>
                        </div>
                        <div class="skill_wrap">
                            <p class="animated rotateInDownLeft">SKILLS</p>
                            <span>
							Negotiating counting remodeling writing acing singing reporting incorporating selling advertising hosting competing twitting parenting gambling dating suing organizing funding debating advising presbyterianing
						</span>
                        </div>
                        <div class="skill_wrap">
                            <p class="animated rotateInDownLeft">CHARACTER</p>
                            <span>
							Adjusted calm ambitious competitive sociable direct hostile careless ignorant inquisitive bold confident mischievous charming interesting daring colorful lazy self-promoting
						</span>
                        </div>
                        <div class="skill_wrap">
                            <p class="animated rotateInDownLeft">LIKES ðŸ˜ƒ</p>
                            <span>
							Billions filet-o-fish big mac china quarter pounder diet coke tariffs bible artof deal patriots beautiful models gold real estate war protesters construction russians banks sports women mexico red hat koreans golf everybody
						</span>
                        </div>
                        <div class="skill_wrap">
                            <p class="animated rotateInDownLeft">DISLIKES ðŸ˜ž</p>
                            <span>
							Dogs media cnn germans mexicans immigrants shithole countries unattractive women blacks sushi hot-dogs alcohol fruit christmas parties liberals
						</span>
                        </div>
                        <div class="skill_wrap">
                            <p class="animated rotateInDownLeft">WANTS ðŸ¤©</p>
                            <span>
							Be healthy grow a tree build trump airport have a taste do a harlem shake in congress to golf more often win all the court suits
						</span>
                        </div>
                    </div>
